name: $name
version: $version
main: com.readutf.mcmatchmaker.server.MatchInstanceSpigot
description: $description
load: POSTWORLD
authors:
  - readUTF
depend:
  - InariDemo
api-version: "$apiVersion"